# Generated by Django 2.2.1 on 2019-05-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190524_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='files',
            field=models.FileField(default='default.png', upload_to='profile_pict'),
        ),
    ]
