# Generated by Django 2.2.1 on 2019-05-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='living_time',
            field=models.IntegerField(default=200),
        ),
    ]
