# Generated by Django 2.2.1 on 2019-05-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190526_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(default='default.txt', upload_to='files'),
        ),
    ]
